---
# file: roles/scrapingpython/tasks/main.yml

- name: install binary python for twisted
  sudo: yes
  apt: pkg=python-twisted state=installed

- name: transfer requirements file to server
  copy: src=requirements.txt dest=/home/deployer/requirements.txt owner=deployer mode=0777

- name: Install the scraping repo requirements package
  sudo: yes
  pip: requirements=/home/deployer/requirements.txt state=present